"use client";

import { FormEvent, createElement, useMemo, useState } from "react";
import type { LucideIcon } from "lucide-react";
import { CalendarDays, LayoutDashboard, MessageCircleMore, Settings2, UsersRound, WalletCards } from "lucide-react";

type View = "overview" | "appointments" | "patients" | "finance" | "messages" | "settings";

const navItems: { id: View; label: string; icon: LucideIcon; badge?: string }[] = [
  { id: "overview", label: "نظرة عامة", icon: LayoutDashboard },
  { id: "appointments", label: "المواعيد", icon: CalendarDays, badge: "8" },
  { id: "patients", label: "المرضى", icon: UsersRound },
  { id: "finance", label: "المدفوعات", icon: WalletCards },
  { id: "messages", label: "الرسائل", icon: MessageCircleMore, badge: "3" },
  { id: "settings", label: "الإعدادات", icon: Settings2 },
];

const appointments = [
  { time: "09:00", period: "ص", name: "عمر خالد", type: "كشف جديد", status: "حضر", tone: "mint", initials: "عخ" },
  { time: "10:30", period: "ص", name: "سارة أحمد", type: "متابعة دورية", status: "التالي", tone: "orange", initials: "سأ" },
  { time: "12:00", period: "م", name: "مريم حسن", type: "استشارة فيديو", status: "مؤكد", tone: "blue", initials: "مح" },
  { time: "01:30", period: "م", name: "يوسف علي", type: "كشف جديد", status: "مؤكد", tone: "purple", initials: "يع" },
];

const patients = [
  { name: "سارة أحمد", phone: "010 2486 1150", last: "اليوم، 10:30 ص", visits: 7, initials: "سأ", tone: "orange", note: "متابعة دورية" },
  { name: "عمر خالد", phone: "011 8352 4207", last: "اليوم، 09:00 ص", visits: 2, initials: "عخ", tone: "mint", note: "كشف جديد" },
  { name: "مريم حسن", phone: "012 6509 3321", last: "14 يوليو، 12:00 م", visits: 5, initials: "مح", tone: "blue", note: "استشارة فيديو" },
  { name: "يوسف علي", phone: "010 9921 7355", last: "12 يوليو، 01:30 م", visits: 3, initials: "يع", tone: "purple", note: "متابعة" },
  { name: "هدى محمود", phone: "015 3364 1902", last: "10 يوليو، 05:00 م", visits: 11, initials: "هم", tone: "rose", note: "جلسة علاج" },
  { name: "كريم أشرف", phone: "011 8720 4476", last: "8 يوليو، 06:30 م", visits: 4, initials: "كأ", tone: "sand", note: "كشف جديد" },
];

const titleMap: Record<View, { title: string; subtitle: string }> = {
  overview: { title: "صباح الخير، د. ريم", subtitle: "الخميس، 16 يوليو • يوم هادئ ومنظّم قدامك" },
  appointments: { title: "المواعيد", subtitle: "نظّم يومك وتابع حالة كل حجز في لحظته" },
  patients: { title: "ملفات المرضى", subtitle: "كل تاريخ مرضاك ومتابعاتهم في مكان واحد" },
  finance: { title: "المدفوعات", subtitle: "صورة واضحة عن أداء العيادة المالي" },
  messages: { title: "الرسائل", subtitle: "تواصل سريع وآمن مع مرضاك" },
  settings: { title: "الإعدادات", subtitle: "خصّص النظام بما يناسب طريقة عمل عيادتك" },
};

function Avatar({ initials, tone = "orange", small = false }: { initials: string; tone?: string; small?: boolean }) {
  return <span className={`avatar avatar-${tone} ${small ? "avatar-small" : ""}`}>{initials}</span>;
}

function Overview({ onBook, onNavigate }: { onBook: () => void; onNavigate: (view: View) => void }) {
  const stats = [
    { label: "مواعيد اليوم", value: "12", detail: "3 حجوزات جديدة", icon: "◷", tone: "orange", trend: "+18%" },
    { label: "إجمالي المرضى", value: "1,248", detail: "28 مريض هذا الشهر", icon: "♙", tone: "mint", trend: "+12%" },
    { label: "الإيراد الشهري", value: "84.6K", suffix: "ج.م", detail: "مقارنة بالشهر الماضي", icon: "⌁", tone: "blue", trend: "+9.4%" },
    { label: "متوسط التقييم", value: "4.9", detail: "من 326 تقييم", icon: "☆", tone: "purple", trend: "ممتاز" },
  ];
  return <>
    <section className="hero-card">
      <div className="hero-copy"><span className="eyebrow"><i /> نبضة العيادة</span><h2>كل حاجة ماشية<br /><em>على أفضل ما يكون.</em></h2><p>نسبة امتلاء جدول اليوم وصلت إلى 78%، وفيه 4 فترات متاحة تقدر تستقبل حجوزات جديدة.</p><div className="hero-actions"><button className="primary-button" onClick={onBook}><span>＋</span> حجز موعد جديد</button><button className="ghost-button" onClick={() => onNavigate("appointments")}>عرض الجدول <span>←</span></button></div></div>
      <div className="pulse-visual" aria-label="نسبة إشغال اليوم 78 بالمائة"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="pulse-ring"><strong>78<small>%</small></strong><span>إشغال اليوم</span></div><span className="floating-note note-one">4 فترات متاحة</span><span className="floating-note note-two">12 موعد</span></div>
    </section>
    <section className="stats-grid" aria-label="مؤشرات الأداء">{stats.map((stat) => <article className="stat-card" key={stat.label}><div className="stat-top"><span className={`icon-box ${stat.tone}`}>{stat.icon}</span><span className={`trend ${stat.tone}`}>{stat.trend}</span></div><p>{stat.label}</p><div className="stat-value"><strong>{stat.value}</strong>{stat.suffix && <small>{stat.suffix}</small>}</div><span className="stat-detail">{stat.detail}</span></article>)}</section>
    <section className="dashboard-grid">
      <article className="panel schedule-panel"><div className="panel-header"><div><span className="section-kicker">جدول اليوم</span><h3>المواعيد القادمة</h3></div><button className="text-button" onClick={() => onNavigate("appointments")}>عرض الكل <span>←</span></button></div><div className="appointment-list">{appointments.map((item, index) => <div className={`appointment-row ${index === 1 ? "is-next" : ""}`} key={item.time}><div className="time-cell"><strong>{item.time}</strong><span>{item.period}</span></div><span className="timeline-dot" /><Avatar initials={item.initials} tone={item.tone} /><div className="patient-cell"><strong>{item.name}</strong><span>{item.type}</span></div><span className={`status-pill status-${item.status === "حضر" ? "done" : item.status === "التالي" ? "next" : "confirmed"}`}>{item.status}</span><button className="more-button" aria-label={`المزيد عن موعد ${item.name}`}>•••</button></div>)}</div></article>
      <article className="panel insight-panel"><div className="panel-header"><div><span className="section-kicker">هذا الأسبوع</span><h3>تدفق الحجوزات</h3></div><span className="mini-select">آخر 7 أيام⌄</span></div><div className="chart-summary"><strong>68</strong><span>موعدًا</span><em>+14%</em></div><div className="bars" aria-label="رسم بياني للحجوزات الأسبوعية">{[46, 68, 54, 86, 70, 96, 62].map((height, i) => <div className="bar-wrap" key={i}><span className={i === 5 ? "active" : ""} style={{ height: `${height}%` }} /><small>{["س", "ح", "ن", "ث", "ر", "خ", "ج"][i]}</small></div>)}</div><div className="insight-note"><span>✦</span><p><strong>الخميس هو يومك الأكثر نشاطًا</strong><br />متوسط 15 حجزًا خلال آخر 4 أسابيع.</p></div></article>
      <article className="panel requests-panel"><div className="panel-header"><div><span className="section-kicker">يحتاج مراجعتك</span><h3>طلبات الحجز</h3></div><span className="count-badge">3</span></div><div className="request-item"><Avatar initials="رن" tone="rose" small /><div><strong>ريم نبيل</strong><span>غدًا، 11:00 ص • كشف جديد</span></div><button className="accept">قبول</button><button className="decline">×</button></div><div className="request-item"><Avatar initials="ما" tone="blue" small /><div><strong>محمد أمين</strong><span>السبت، 04:30 م • متابعة</span></div><button className="accept">قبول</button><button className="decline">×</button></div><button className="wide-subtle" onClick={() => onNavigate("appointments")}>مراجعة كل الطلبات</button></article>
      <article className="panel experience-panel"><div className="experience-top"><span>رأي المرضى</span><strong>4.9</strong><div className="stars">★★★★★</div><small>326 تقييمًا موثوقًا</small></div><blockquote>“الحجز كان سهل جدًا والتذكير وصل في معاده. تجربة ممتازة من أول خطوة.”</blockquote><div className="quote-author"><Avatar initials="نه" tone="mint" small /><div><strong>نورا هاني</strong><span>زيارة مؤكدة • منذ يومين</span></div></div></article>
    </section>
  </>;
}

function AppointmentsView({ onBook }: { onBook: () => void }) {
  const [filter, setFilter] = useState("الكل");
  const rows = [...appointments, { time: "03:00", period: "م", name: "هدى محمود", type: "جلسة علاج", status: "مؤكد", tone: "rose", initials: "هم" }, { time: "05:30", period: "م", name: "كريم أشرف", type: "متابعة", status: "مؤكد", tone: "sand", initials: "كأ" }];
  return <section className="view-stack"><div className="action-row"><div className="date-switcher"><button>→</button><strong>الخميس، 16 يوليو</strong><button>←</button><button className="today">اليوم</button></div><button className="primary-button compact" onClick={onBook}><span>＋</span> حجز جديد</button></div><div className="calendar-strip">{[{d:"س",n:"12"},{d:"ح",n:"13"},{d:"ن",n:"14"},{d:"ث",n:"15"},{d:"ر",n:"16",active:true},{d:"خ",n:"17"},{d:"ج",n:"18"}].map((day) => <button key={day.n} className={day.active ? "active" : ""}><span>{day.d}</span><strong>{day.n}</strong>{day.active && <i />}</button>)}</div><div className="panel appointments-table-panel"><div className="table-toolbar"><div className="filter-tabs">{["الكل", "مؤكد", "في الانتظار", "مكتمل"].map(f => <button className={filter === f ? "active" : ""} onClick={() => setFilter(f)} key={f}>{f}</button>)}</div><label className="search-field small"><span>⌕</span><input placeholder="ابحث في المواعيد" /></label></div><div className="data-list">{rows.map((item, index) => <div className="data-row" key={`${item.name}-${item.time}`}><div className="time-cell large"><strong>{item.time}</strong><span>{item.period}</span></div><Avatar initials={item.initials} tone={item.tone} /><div className="data-main"><strong>{item.name}</strong><span>#{2450 + index} • {item.type}</span></div><div className="contact-chip">☏ <span>اتصال</span></div><span className={`status-pill ${index === 0 ? "status-done" : index === 1 ? "status-next" : "status-confirmed"}`}>{index === 0 ? "تم الحضور" : index === 1 ? "التالي" : "مؤكد"}</span><button className="more-button">•••</button></div>)}</div></div></section>;
}

function PatientsView() {
  const [query, setQuery] = useState("");
  const filtered = useMemo(() => patients.filter(p => p.name.includes(query) || p.phone.includes(query)), [query]);
  return <section className="view-stack"><div className="action-row"><label className="search-field page-search"><span>⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="ابحث بالاسم أو رقم الهاتف..." /></label><button className="outline-button">↓ تصدير القائمة</button><button className="primary-button compact">＋ مريض جديد</button></div><div className="micro-stats"><div><span>إجمالي المرضى</span><strong>1,248</strong><em>+28 هذا الشهر</em></div><div><span>مرضى جدد</span><strong>84</strong><em>خلال آخر 30 يوم</em></div><div><span>نسبة العودة</span><strong>76%</strong><em>أفضل من المتوسط</em></div></div><div className="patient-grid">{filtered.map(patient => <article className="patient-card" key={patient.phone}><div className="patient-card-top"><Avatar initials={patient.initials} tone={patient.tone} /><button className="more-button">•••</button></div><h3>{patient.name}</h3><p>{patient.phone}</p><div className="patient-meta"><span><small>آخر زيارة</small>{patient.last}</span><span><small>الزيارات</small>{patient.visits}</span></div><div className="patient-card-bottom"><span>{patient.note}</span><button>عرض الملف ←</button></div></article>)}</div></section>;
}

function FinanceView() {
  const values = [42, 55, 48, 68, 61, 76, 58, 81, 73, 88, 80, 96];
  return <section className="view-stack"><div className="finance-cards"><article className="finance-main"><span>إجمالي الإيرادات • يوليو</span><strong>84,650 <small>ج.م</small></strong><p><em>↑ 9.4%</em> مقارنة بـ 77,380 ج.م الشهر الماضي</p></article><article><span>تم تحصيله</span><strong>72,450 <small>ج.م</small></strong><div className="progress"><i style={{width:"86%"}} /></div><p>86% من الإجمالي</p></article><article><span>مبالغ معلقة</span><strong>12,200 <small>ج.م</small></strong><div className="progress orange"><i style={{width:"34%"}} /></div><p>8 فواتير تحتاج متابعة</p></article></div><div className="finance-layout"><article className="panel revenue-chart"><div className="panel-header"><div><span className="section-kicker">الأداء المالي</span><h3>الإيرادات الشهرية</h3></div><span className="mini-select">2026⌄</span></div><div className="large-bars">{values.map((v,i)=><div key={i}><span style={{height:`${v}%`}} className={i===11?"active":""} /><small>{["أغس","سبت","أكت","نوف","ديس","ينا","فبر","مار","أبر","ماي","يون","يول"][i]}</small></div>)}</div></article><article className="panel transactions"><div className="panel-header"><div><span className="section-kicker">آخر العمليات</span><h3>المدفوعات</h3></div><button className="text-button">عرض الكل</button></div>{patients.slice(0,4).map((p,i)=><div className="transaction" key={p.name}><Avatar initials={p.initials} tone={p.tone} small /><div><strong>{p.name}</strong><span>{i%2===0?"بطاقة بنكية":"نقدي"} • اليوم</span></div><strong className="amount">{[650,450,800,550][i]} ج.م</strong></div>)}</article></div></section>;
}

function MessagesView() {
  const [selected, setSelected] = useState(0);
  const chats = [{name:"سارة أحمد",msg:"تمام يا دكتورة، شكرًا لحضرتك",time:"10:42 ص",tone:"orange",initials:"سأ"},{name:"محمد أمين",msg:"ممكن أغيّر ميعاد المتابعة؟",time:"09:18 ص",tone:"blue",initials:"ما"},{name:"نورا هاني",msg:"وصلني التذكير، شكرًا جدًا",time:"أمس",tone:"mint",initials:"نه"},{name:"عمر خالد",msg:"تم إرسال التحاليل المطلوبة",time:"أمس",tone:"purple",initials:"عخ"}];
  return <section className="messages-shell"><aside className="chat-list"><label className="search-field small"><span>⌕</span><input placeholder="ابحث في المحادثات" /></label>{chats.map((chat,i)=><button className={`chat-preview ${selected===i?"active":""}`} onClick={()=>setSelected(i)} key={chat.name}><Avatar initials={chat.initials} tone={chat.tone} small /><span><strong>{chat.name}</strong><small>{chat.msg}</small></span><time>{chat.time}</time>{i<2&&<i />}</button>)}</aside><article className="conversation"><header><Avatar initials={chats[selected].initials} tone={chats[selected].tone} small /><div><strong>{chats[selected].name}</strong><span><i /> متصل الآن</span></div><button>☏</button><button>•••</button></header><div className="messages-body"><div className="date-label">اليوم</div><div className="bubble inbound">أهلًا يا دكتورة، حبيت أتأكد من ميعاد المتابعة بكرة.</div><div className="bubble outbound">أهلًا يا {chats[selected].name.split(" ")[0]}، الموعد مؤكد بكرة الساعة 10:30 صباحًا.</div><div className="bubble inbound">تمام يا دكتورة، شكرًا لحضرتك <small>10:42 ص</small></div></div><footer><button>＋</button><input placeholder="اكتب رسالتك هنا..." /><button>☺</button><button className="send">←</button></footer></article></section>;
}

function SettingsView() {
  const [reminders, setReminders] = useState(true); const [online, setOnline] = useState(true); const [waitlist, setWaitlist] = useState(false);
  return <section className="settings-layout"><aside className="settings-nav"><button className="active">بيانات العيادة</button><button>مواعيد العمل</button><button>الحجز والتذكيرات</button><button>طرق الدفع</button><button>الفريق والصلاحيات</button></aside><div className="settings-content"><article className="panel form-panel"><div className="panel-header"><div><span className="section-kicker">الملف العام</span><h3>بيانات العيادة</h3></div><button className="primary-button compact">حفظ التغييرات</button></div><div className="clinic-brand"><span className="clinic-logo">ر</span><div><strong>شعار العيادة</strong><p>PNG أو JPG، بحد أقصى 2MB</p><button>تغيير الشعار</button></div></div><div className="form-grid"><label><span>اسم العيادة</span><input defaultValue="عيادة الريم التخصصية" /></label><label><span>التخصص</span><select defaultValue="باطنة"><option>باطنة</option><option>أسنان</option><option>جلدية</option></select></label><label className="full"><span>العنوان</span><input defaultValue="15 شارع التسعين، التجمع الخامس، القاهرة" /></label><label><span>رقم الهاتف</span><input defaultValue="02 2550 1840" /></label><label><span>البريد الإلكتروني</span><input defaultValue="hello@alreem.clinic" /></label></div></article><article className="panel preferences"><div><h3>إعدادات ذكية</h3><p>تحكّم في طريقة استقبال وتنظيم الحجوزات</p></div><Toggle label="تذكير تلقائي للمريض" detail="رسالة قبل الموعد بـ 24 ساعة" checked={reminders} set={setReminders} /><Toggle label="السماح بالحجز أونلاين" detail="إتاحة المواعيد المتوفرة للمرضى" checked={online} set={setOnline} /><Toggle label="قائمة الانتظار الذكية" detail="ملء المواعيد الملغاة تلقائيًا" checked={waitlist} set={setWaitlist} /></article></div></section>;
}

function Toggle({label, detail, checked, set}:{label:string;detail:string;checked:boolean;set:(v:boolean)=>void}) { return <label className="toggle"><span><strong>{label}</strong><small>{detail}</small></span><input type="checkbox" checked={checked} onChange={e=>set(e.target.checked)} /><i /></label>; }

function BookingModal({ onClose }: { onClose: () => void }) {
  const [done, setDone] = useState(false);
  const submit = (e: FormEvent) => { e.preventDefault(); setDone(true); };
  return <div className="modal-backdrop" onMouseDown={e => { if (e.target === e.currentTarget) onClose(); }}><div className="booking-modal" role="dialog" aria-modal="true" aria-labelledby="booking-title"><button className="modal-close" onClick={onClose} aria-label="إغلاق">×</button>{done ? <div className="success-state"><div className="success-mark">✓</div><span>تم الحجز بنجاح</span><h2>الموعد اتضاف للجدول</h2><p>الخميس، 16 يوليو في تمام الساعة 03:30 م. هنرسل رسالة تأكيد للمريض تلقائيًا.</p><button className="primary-button" onClick={onClose}>العودة للجدول</button></div> : <><div className="modal-heading"><span className="eyebrow"><i /> حجز سريع</span><h2 id="booking-title">موعد جديد</h2><p>أضف بيانات المريض واختار الوقت المناسب.</p></div><form onSubmit={submit}><label><span>اسم المريض</span><input required placeholder="اكتب الاسم بالكامل" /></label><div className="form-row"><label><span>رقم الهاتف</span><input required placeholder="01X XXXX XXXX" /></label><label><span>نوع الزيارة</span><select><option>كشف جديد</option><option>متابعة دورية</option><option>استشارة فيديو</option></select></label></div><label><span>التاريخ</span><div className="date-options"><button type="button" className="selected"><small>الخميس</small><strong>16</strong><span>يوليو</span></button><button type="button"><small>السبت</small><strong>18</strong><span>يوليو</span></button><button type="button"><small>الأحد</small><strong>19</strong><span>يوليو</span></button></div></label><label><span>الوقت المتاح</span><div className="time-options"><button type="button">12:30 م</button><button type="button" className="selected">03:30 م</button><button type="button">05:00 م</button><button type="button">06:30 م</button></div></label><button className="primary-button submit-booking" type="submit">تأكيد الحجز <span>←</span></button></form></>}</div></div>;
}

export default function Home() {
  const [active, setActive] = useState<View>("overview"); const [bookingOpen, setBookingOpen] = useState(false); const [noticesOpen, setNoticesOpen] = useState(false); const [menuOpen, setMenuOpen] = useState(false);
  const selectView = (view: View) => { setActive(view); setMenuOpen(false); };
  return <main className="app-shell" dir="rtl"><aside className={`sidebar ${menuOpen ? "open" : ""}`}><div className="brand"><span className="brand-mark">ر</span><div><strong>الريم</strong><small>إدارة عيادتك بذكاء</small></div></div><nav aria-label="القائمة الرئيسية">{navItems.map(item => <button key={item.id} className={active === item.id ? "active" : ""} onClick={() => selectView(item.id)}><span className="nav-icon">{createElement(item.icon, { size: 20, strokeWidth: 1.9 })}</span><span>{item.label}</span>{item.badge && <small>{item.badge}</small>}</button>)}</nav><div className="upgrade-card"><div className="spark">✦</div><strong>خلي عيادتك أذكى</strong><p>فعّل التقارير المتقدمة وأتمتة المتابعة.</p><button>اكتشف Pro</button></div><div className="sidebar-user"><Avatar initials="ر" tone="orange" small /><div><strong>د. ريم</strong><span>مديرة العيادة</span></div><button>⌄</button></div></aside>{menuOpen && <button className="mobile-overlay" aria-label="إغلاق القائمة" onClick={() => setMenuOpen(false)} />}<section className="workspace"><header className="topbar"><button className="menu-toggle" onClick={() => setMenuOpen(true)} aria-label="فتح القائمة">☰</button><div className="page-title"><h1>{titleMap[active].title}</h1><p>{titleMap[active].subtitle}</p></div><div className="topbar-actions"><label className="search-field header-search"><span>⌕</span><input placeholder="ابحث عن مريض، موعد..." /><kbd>⌘ K</kbd></label><div className="notification-wrap"><button className="icon-button" onClick={() => setNoticesOpen(!noticesOpen)} aria-label="الإشعارات">♢<i /></button>{noticesOpen && <div className="notifications"><div><strong>الإشعارات</strong><button onClick={() => setNoticesOpen(false)}>×</button></div><p><span className="notice-icon orange">◷</span><b>موعد بعد 15 دقيقة</b><small>سارة أحمد • متابعة دورية</small></p><p><span className="notice-icon mint">✓</span><b>تم تأكيد حجز جديد</b><small>محمد أمين • السبت 04:30 م</small></p><p><span className="notice-icon blue">✉</span><b>رسالة جديدة من نورا</b><small>منذ 8 دقائق</small></p></div>}</div><button className="top-avatar" aria-label="حساب د. ريم"><Avatar initials="ر" tone="orange" small /></button></div></header><div className="content-area">{active === "overview" && <Overview onBook={() => setBookingOpen(true)} onNavigate={selectView} />}{active === "appointments" && <AppointmentsView onBook={() => setBookingOpen(true)} />}{active === "patients" && <PatientsView />}{active === "finance" && <FinanceView />}{active === "messages" && <MessagesView />}{active === "settings" && <SettingsView />}</div></section>{bookingOpen && <BookingModal onClose={() => setBookingOpen(false)} />}<nav className="mobile-nav" aria-label="القائمة السريعة">{navItems.slice(0,5).map(item => <button key={item.id} className={active === item.id ? "active" : ""} onClick={() => selectView(item.id)}><span>{createElement(item.icon, { size: 18, strokeWidth: 1.9 })}</span><small>{item.label}</small></button>)}</nav></main>;
}
