"use client";

import { useCallback, useEffect, useState } from "react";
import { ArrowRight, Bell, CheckCheck, ChevronLeft, ChevronRight, Trash2 } from "lucide-react";
import type { ClinicNotification, NotificationType } from "@/lib/notification-types";
type Result={items:ClinicNotification[];page:number;pages:number;total:number};type Api<T>={success:boolean;data:T;message:string};
async function api<T>(url:string,init?:RequestInit){const response=await fetch(url,{...init,headers:{"Content-Type":"application/json"},cache:"no-store"});const body=await response.json() as Api<T>;if(!response.ok||!body.success)throw new Error(body.message||"تعذر التنفيذ");return body.data;}
const labels:Record<NotificationType,string>={APPOINTMENT_CREATED:"حجز جديد",APPOINTMENT_CONFIRMED:"تأكيد",APPOINTMENT_CANCELLED:"إلغاء",APPOINTMENT_UPDATED:"تعديل",APPOINTMENT_REMINDER:"تذكير",PATIENT_CREATED:"مريض جديد",PATIENT_ARRIVED:"وصول",SYSTEM:"النظام"};
const date=new Intl.DateTimeFormat("ar-EG-u-nu-latn",{dateStyle:"medium",timeStyle:"short",timeZone:"Africa/Cairo"});
export function NotificationsPage(){const [result,setResult]=useState<Result>({items:[],page:1,pages:1,total:0}),[page,setPage]=useState(1),[type,setType]=useState("all"),[read,setRead]=useState("all"),[loading,setLoading]=useState(true),[error,setError]=useState("");const load=useCallback(async()=>{setLoading(true);try{setResult(await api<Result>(`/api/notifications?page=${page}&pageSize=15&type=${type}&read=${read}`));setError("");}catch(e){setError(e instanceof Error?e.message:"تعذر التحميل");}finally{setLoading(false);}},[page,type,read]);useEffect(()=>{void load();},[load]);async function remove(id:string){await api(`/api/notifications/${id}`,{method:"DELETE"});void load();}async function open(item:ClinicNotification){if(!item.isRead)await api(`/api/notifications/${item.id}/read`,{method:"PATCH"});location.href=item.actionUrl||"/";}return <main className="notifications-page" dir="rtl"><header><a href="/"><ArrowRight size={18}/> العودة للوحة التحكم</a><div><span className="section-kicker">مركز التنبيهات</span><h1>الإشعارات</h1><p>كل حجوزات العيادة وتحديثاتها في سجل واحد.</p></div><button onClick={async()=>{await api("/api/notifications/read-all",{method:"PATCH"});void load();}}><CheckCheck size={18}/> تعليم الكل كمقروء</button></header><section className="notification-filters"><select value={type} onChange={e=>{setType(e.target.value);setPage(1)}}><option value="all">كل الأنواع</option>{Object.entries(labels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><select value={read} onChange={e=>{setRead(e.target.value);setPage(1)}}><option value="all">الكل</option><option value="unread">غير مقروء</option><option value="read">مقروء</option></select><strong>{result.total} إشعار</strong></section><section className="notifications-table">{loading?<p className="notifications-state">جاري تحميل الإشعارات...</p>:error?<p className="notifications-state error">{error}</p>:result.items.length?result.items.map(item=><article key={item.id} className={item.isRead?"":"unread"}><button className="notification-row-main" onClick={()=>void open(item)}><span className={`notification-type priority-${item.priority}`}><Bell size={18}/></span><span><b>{item.title}</b><p>{item.message}</p><small>{labels[item.type]} • {date.format(new Date(item.createdAt))}</small></span></button><button className="notification-row-delete" onClick={()=>void remove(item.id)} aria-label="حذف"><Trash2 size={17}/></button></article>):<p className="notifications-state">لا توجد إشعارات تطابق الاختيار.</p>}</section><footer className="notification-pagination"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}><ChevronRight size={17}/> السابق</button><span>صفحة {result.page} من {result.pages}</span><button disabled={page>=result.pages} onClick={()=>setPage(p=>p+1)}>التالي <ChevronLeft size={17}/></button></footer></main>}
