"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { Bell, CheckCheck, ExternalLink, X } from "lucide-react";
import type { ClinicNotification } from "@/lib/notification-types";

type Api<T>={success:boolean;data:T;message:string};
async function request<T>(url:string,init?:RequestInit){const response=await fetch(url,{...init,headers:{"Content-Type":"application/json",...(init?.headers||{})},cache:"no-store"});const body=await response.json() as Api<T>;if(!response.ok||!body.success)throw new Error(body.message||"تعذر تنفيذ الطلب");return body.data;}
const relative=new Intl.RelativeTimeFormat("ar-EG-u-nu-latn",{numeric:"auto"});
function ago(value:string){const seconds=Math.round((new Date(value).getTime()-Date.now())/1000),abs=Math.abs(seconds);if(abs<60)return relative.format(seconds,"second");if(abs<3600)return relative.format(Math.round(seconds/60),"minute");if(abs<86400)return relative.format(Math.round(seconds/3600),"hour");return relative.format(Math.round(seconds/86400),"day");}

export function NotificationCenter(){
  const [open,setOpen]=useState(false),[items,setItems]=useState<ClinicNotification[]>([]),[count,setCount]=useState(0),[loading,setLoading]=useState(false);const root=useRef<HTMLDivElement>(null),latest=useRef<string|null>(null);
  const load=useCallback(async()=>{try{const [list,unread]=await Promise.all([request<{items:ClinicNotification[]}>("/api/notifications?pageSize=6"),request<{count:number}>("/api/notifications/unread-count")]);setItems(list.items);setCount(unread.count);}catch{/* dashboard handles auth state */}},[]);
  useEffect(()=>{void load().then(()=>{latest.current=new Date().toISOString()});const poll=async()=>{if(document.visibilityState!=="visible")return;try{const data=await request<{items:ClinicNotification[];count:number}>(`/api/notifications/latest?after=${encodeURIComponent(latest.current||new Date(0).toISOString())}`);if(data.items.length)setItems(current=>[...data.items,...current].slice(0,6));setCount(data.count);latest.current=new Date().toISOString();}catch{}};const timer=setInterval(()=>void poll(),25000);const visible=()=>{if(document.visibilityState==="visible")void load();};document.addEventListener("visibilitychange",visible);return()=>{clearInterval(timer);document.removeEventListener("visibilitychange",visible);};},[load]);
  useEffect(()=>{const close=(event:MouseEvent)=>{if(!root.current?.contains(event.target as Node))setOpen(false)};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close);},[]);
  async function read(item:ClinicNotification){if(!item.isRead){await request(`/api/notifications/${item.id}/read`,{method:"PATCH"});setCount(c=>Math.max(0,c-1));}location.href=item.actionUrl||"/notifications";}
  async function readAll(){setLoading(true);try{await request("/api/notifications/read-all",{method:"PATCH"});setItems(v=>v.map(x=>({...x,isRead:true})));setCount(0);}finally{setLoading(false);}}
  async function remove(id:string){await request(`/api/notifications/${id}`,{method:"DELETE"});setItems(v=>v.filter(x=>x.id!==id));void load();}
  return <div className="notification-center" ref={root}><button className="notification-bell" aria-label={`الإشعارات، ${count} غير مقروء`} aria-expanded={open} onClick={()=>{setOpen(v=>!v);if(!open)void load();}}><Bell size={20}/>{count>0&&<b>{count>99?"99+":count}</b>}</button>{open&&<section className="notification-popover"><header><div><strong>الإشعارات</strong><small>{count?`${count} غير مقروء`:"كل شيء واضح"}</small></div><button onClick={()=>setOpen(false)} aria-label="إغلاق"><X size={18}/></button></header>{items.length?<div className="notification-list">{items.map(item=><article key={item.id} className={`${item.isRead?"":"unread"} priority-${item.priority}`}><button className="notification-content" onClick={()=>void read(item)}><span className="notification-dot"/><span><strong>{item.title}</strong><p>{item.message}</p><small>{ago(item.createdAt)}</small></span></button><button className="notification-delete" onClick={()=>void remove(item.id)} aria-label="حذف الإشعار"><X size={15}/></button></article>)}</div>:<div className="notification-empty"><Bell size={24}/><strong>لا توجد إشعارات جديدة</strong><span>ستظهر التحديثات الجديدة هنا.</span></div>}<footer><button onClick={()=>void readAll()} disabled={!count||loading}><CheckCheck size={16}/> تعليم الكل كمقروء</button><a href="/notifications">عرض كل الإشعارات <ExternalLink size={14}/></a></footer></section>}</div>;
}
