"use client";

import { useEffect, useState } from "react";
import { BellRing, CheckCircle2, Send, Smartphone, XCircle } from "lucide-react";
import type { NotificationPreferences } from "@/lib/notification-types";

type Payload={preferences:NotificationPreferences;push:{configured:boolean;publicKey:string|null}};type Api<T>={success:boolean;data:T;message:string};
async function api<T>(url:string,init?:RequestInit){const response=await fetch(url,{...init,headers:{"Content-Type":"application/json"},cache:"no-store"});const body=await response.json() as Api<T>;if(!response.ok||!body.success)throw new Error(body.message||"تعذر التنفيذ");return body.data;}
function decode(value:string){const padding="=".repeat((4-value.length%4)%4),raw=atob((value+padding).replace(/-/g,"+").replace(/_/g,"/"));return Uint8Array.from([...raw].map(x=>x.charCodeAt(0)));}

export function PushSettings(){
  const [data,setData]=useState<Payload|null>(null),[subscribed,setSubscribed]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[isIos,setIsIos]=useState(false);
  useEffect(()=>{setIsIos(/iPad|iPhone|iPod/.test(navigator.userAgent));api<Payload>("/api/notifications/preferences").then(async value=>{setData(value);const reg=await navigator.serviceWorker?.ready;setSubscribed(Boolean(await reg?.pushManager.getSubscription()));}).catch(e=>setMessage(e.message));},[]);
  async function save(patch:Partial<NotificationPreferences>){if(!data)return;const preferences=await api<NotificationPreferences>("/api/notifications/preferences",{method:"PATCH",body:JSON.stringify(patch)});setData({...data,preferences});}
  async function enable(){if(!data?.push.publicKey)return setMessage("أضف مفاتيح VAPID في إعدادات النشر أولًا.");setBusy(true);setMessage("");try{if(!("Notification" in window)||!("serviceWorker" in navigator)||!("PushManager" in window))throw new Error("هذا المتصفح لا يدعم إشعارات الويب.");const permission=await Notification.requestPermission();if(permission!=="granted")throw new Error("لم يتم السماح بالإشعارات من إعدادات المتصفح.");const reg=await navigator.serviceWorker.ready;const subscription=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:decode(data.push.publicKey)});await api("/api/push/subscribe",{method:"POST",body:JSON.stringify({...subscription.toJSON(),deviceName:navigator.platform})});await save({pushEnabled:true});setSubscribed(true);setMessage("تم تفعيل الإشعارات على هذا الجهاز.");}catch(e){setMessage(e instanceof Error?e.message:"تعذر التفعيل");}finally{setBusy(false);}}
  async function disable(){setBusy(true);try{const reg=await navigator.serviceWorker.ready,subscription=await reg.pushManager.getSubscription();if(subscription){await api("/api/push/unsubscribe",{method:"DELETE",body:JSON.stringify({endpoint:subscription.endpoint})});await subscription.unsubscribe();}setSubscribed(false);setMessage("تم إيقاف إشعارات هذا الجهاز.");}finally{setBusy(false);}}
  if(!data)return <article className="panel push-settings-card"><p>{message||"جاري تحميل إعدادات الإشعارات..."}</p></article>;
  const p=data.preferences;const toggles:Array<[keyof NotificationPreferences,string,string]>=[["newBookings","الحجوزات الجديدة","تنبيه عند وصول حجز جديد"],["cancellations","الإلغاءات","تنبيه عند إلغاء موعد"],["appointmentUpdates","تعديلات المواعيد","التأكيد أو تغيير اليوم والوقت"],["patientArrivals","وصول المريض","تنبيه عند تسجيل وصول المريض"],["appointmentReminders","تذكير قبل الموعد","تنبيه قبل بدء الموعد"],["pushEnabled","إشعارات المتصفح","السماح بإرسال التنبيهات للأجهزة المسجلة"],["inAppEnabled","إشعارات داخل المنصة","حفظ وإظهار التنبيهات في مركز الإشعارات"]];
  return <article className="panel push-settings-card"><div className="panel-header"><div><span className="section-kicker">الإشعارات الفورية</span><h3>تنبيهات الأجهزة</h3></div><span className={`push-state ${subscribed?"on":"off"}`}>{subscribed?<CheckCircle2 size={16}/>:<XCircle size={16}/>} {subscribed?"مفعلة":"غير مفعلة"}</span></div><div className="push-device"><Smartphone size={22}/><div><strong>هذا الجهاز</strong><small>{subscribed?"سيستقبل الإشعارات حتى عند إغلاق المنصة":"فعّل الإذن من الزر لتسجيل هذا الجهاز"}</small></div>{subscribed?<button onClick={()=>void disable()} disabled={busy}>إيقاف</button>:<button onClick={()=>void enable()} disabled={busy}><BellRing size={16}/> تفعيل</button>}</div>{message&&<p className="push-message">{message}</p>}<div className="notification-toggles">{toggles.map(([key,title,description])=><label key={key}><span><strong>{title}</strong><small>{description}</small></span><input type="checkbox" checked={Boolean(p[key])} onChange={e=>void save({[key]:e.target.checked})}/><i/></label>)}</div><label className="reminder-select"><span>موعد التذكير</span><select value={p.reminderMinutes} onChange={e=>void save({reminderMinutes:Number(e.target.value) as 15|30|60})}><option value="15">قبل 15 دقيقة</option><option value="30">قبل 30 دقيقة</option><option value="60">قبل 60 دقيقة</option></select></label><button className="push-test" disabled={!subscribed||busy} onClick={async()=>{setBusy(true);try{await api("/api/push/test",{method:"POST"});setMessage("تم إرسال الإشعار التجريبي.");}catch(e){setMessage(e instanceof Error?e.message:"تعذر الإرسال");}finally{setBusy(false);}}}><Send size={16}/> إرسال إشعار تجريبي</button>{isIos&&<p className="ios-push-note">على iPhone أو iPad: افتح قائمة المشاركة، اختر «إضافة إلى الشاشة الرئيسية»، افتح المنصة من الأيقونة الجديدة، ثم اضغط «تفعيل».</p>}</article>;
}
